In [3]:
import pypsa
import matplotlib.pyplot as plt
import pandas as pd

from pea import Pea
from pea import carriers as cs

%load_ext autoreload
%autoreload 2

In [38]:
n365 = pypsa.Network("./result/test365h2045.nc")
n3 = pypsa.Network("./result/flex3h2045.nc")

WARNING:pypsa.io:The following Link have buses which are not defined:
Index(['FR4 0 waste CHP-2045', 'IT3 0 waste CHP-2045',
       'FR4 0 waste CHP CC-2045', 'IT3 0 waste CHP CC-2045',
       'IT3 0 urban central gas CHP-2010'],
      dtype='object', name='name')
INFO:pypsa.io:Imported network test365h2045.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores
INFO:pypsa.io:Imported network flex3h2045.nc has buses, carriers, generators, global_constraints, lines, links, loads, storage_units, stores

In [45]:
n3.generators_t.p

Generator,AT0 0 onwind-2005,AT0 0 onwind-2010,AT0 0 onwind-2015,AT0 0 onwind-2020,AT0 0 onwind-2030,AT0 0 ror,AT0 0 solar rooftop-2030,AT0 0 solar-2005,AT0 0 solar-2010,AT0 0 solar-2015,...,SE1 0 onwind-2030,SE1 0 ror,SE1 0 solar rooftop-2030,SE1 0 solar-2015,SE1 0 solar-2020,SE1 0 solar-2030,SE1 0 solar-hsat-2030,SE1 0 solid biomass,SE1 0 unsustainable solid biomass,SE1 0 urban central heat vent
snapshot,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,733.399750,180.324667,1393.444797,697.481700,0.061149,1292.195922,0.000000,0.000000,0.000000,0.000000,...,0.008595,422.278533,0.000000,0.000000,0.000000,0.000000,0.000000,0.002002,0.002003,-0.000974
2019-01-01 03:00:00,736.394851,181.061223,1399.135257,700.330124,0.061590,1284.855828,0.000000,0.000000,0.000000,0.000000,...,0.008525,420.240772,0.000000,0.000000,0.000000,0.000000,0.000000,0.001952,0.001956,-0.000958
2019-01-01 06:00:00,734.094939,180.495744,1394.765452,698.142851,0.061384,1276.033762,0.000000,0.000000,0.000000,0.000000,...,0.007785,417.695491,1800.390732,9.893251,106.710321,0.001622,0.003186,0.001923,0.001929,-0.000951
2019-01-01 09:00:00,706.475852,173.704730,1342.289951,671.876390,0.058760,1269.361457,0.010907,4.712656,14.525581,181.771859,...,0.006546,416.166755,6211.953146,34.137949,368.190574,0.007692,0.007747,0.001901,0.001907,-0.000941
2019-01-01 12:00:00,656.189725,161.340629,1246.747341,624.053012,0.054591,1275.667119,0.002175,1.343017,4.141303,51.834394,...,0.006324,415.274888,4140.762463,22.755241,245.427805,0.004670,0.005835,0.001883,0.001890,-0.000938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-31 09:00:00,539.130419,132.559002,1024.336626,512.726674,0.045420,1412.432023,0.018283,7.145417,22.021163,275.553139,...,0.002735,644.693666,7000.033372,38.469001,414.901316,0.009161,0.009131,0.002650,0.002666,-0.000922
2019-12-31 12:00:00,490.220144,120.533065,931.408254,466.211757,0.041307,1412.326816,0.006264,2.702573,8.329967,104.240175,...,0.002744,644.530701,4228.194697,23.235713,250.610002,0.004884,0.006025,0.002650,0.002666,-0.000922
2019-12-31 15:00:00,386.324373,94.987442,734.008720,367.404236,0.032613,1404.861287,0.000000,0.000000,0.000000,0.000000,...,0.002550,644.372216,0.000000,0.000000,0.000000,0.000000,0.000000,0.002648,0.002665,-0.000924
2019-12-31 18:00:00,298.432600,73.376855,567.016383,283.816923,0.024960,1397.708475,0.000000,0.000000,0.000000,0.000000,...,0.002657,644.207835,0.000000,0.000000,0.000000,0.000000,0.000000,0.002643,0.002663,-0.000923
2019-12-31 21:00:00,310.347559,76.306443,589.654571,295.148350,0.025972,1396.054361,0.000000,0.000000,0.000000,0.000000,...,0.002836,644.055116,0.000000,0.000000,0.000000,0.000000,0.000000,0.002623,0.002657,-0.000927

In [ ]:
n365.generators_t.p['AT0 0 onwind-2045']

Generator,AT0 0 onwind-2020,AT0 0 onwind-2040,AT0 0 onwind-2045,AT0 0 ror,AT0 0 solar rooftop-2045,AT0 0 solar-2010,AT0 0 solar-2015,AT0 0 solar-2020,AT0 0 solar-2045,AT0 0 solar-hsat-2045,...,SE1 0 onwind-2045,SE1 0 ror,SE1 0 solar rooftop-2030,SE1 0 solar rooftop-2045,SE1 0 solar-2015,SE1 0 solar-2020,SE1 0 solar-2045,SE1 0 solar-hsat-2045,SE1 0 solid biomass,SE1 0 urban central heat vent
snapshot,,,,,,,,,,,,,,,,,,,,,
2019-01-01 00:00:00,311.461555,21070.511928,368.595854,1227.136699,4.933594e-12,1.841121,23.037025,30.031383,2.167816e-12,1.155386e-12,...,5.028800e-11,416.749834,1259.334123,0.000004,6.921012,74.642737,580.135147,2.055567e-11,5.702615e-12,-3.006416e-12
2019-01-16 05:00:00,203.532678,14043.335271,245.666321,1159.118349,6.032982e-12,1.752291,21.925537,28.582432,2.790914e-12,1.626303e-12,...,3.749292e-11,396.531792,1285.436977,0.000004,7.064467,76.189895,592.159901,2.478906e-11,5.702615e-12,-3.006416e-12
2019-01-31 10:00:00,370.708352,25316.319616,442.869659,1238.093968,5.401151e-12,2.013065,25.188484,32.836054,2.383671e-12,1.488310e-12,...,5.067528e-11,382.940459,1723.448857,0.000006,9.471680,102.151556,793.938032,3.128912e-11,5.702615e-12,-3.006416e-12
2019-02-15 15:00:00,288.722747,20082.618882,351.314200,1262.118731,1.883421e-11,5.848007,73.173191,95.389579,8.766235e-12,5.798683e-12,...,3.078143e-11,394.569446,2484.994519,0.000008,13.656960,147.289579,1144.757880,4.845514e-11,5.702615e-12,-1.274724e-11
2019-03-02 20:00:00,309.540965,21123.362739,369.520396,1810.136328,7.565797e-12,3.691341,46.187903,60.211186,3.733919e-12,2.658048e-12,...,3.199123e-11,396.782064,2273.849008,0.000008,12.496553,134.774649,1047.489863,4.523728e-11,5.702615e-12,-4.630940e-12
2019-03-18 01:00:00,350.020737,23986.365244,419.604175,1832.229627,2.504919e-11,9.075345,113.555263,148.032203,1.128987e-11,8.517866e-12,...,2.831033e-11,432.221038,2866.892745,0.000010,15.755785,169.925295,1320.686236,6.142818e-11,5.702615e-12,-1.306511e-11
2019-04-02 06:00:00,192.477172,13537.301385,236.814045,2987.558244,3.965773e-11,11.994743,150.084239,195.651879,1.873240e-11,1.501738e-11,...,2.215456e-11,461.907858,2252.703516,0.000008,12.380342,133.521322,1037.748808,4.636080e-11,5.702615e-12,-1.287433e-11
2019-04-17 11:00:00,173.681603,12121.912757,212.054021,3162.058632,3.637714e-11,12.410176,155.282342,202.428198,1.643726e-11,1.353718e-11,...,2.529259e-11,693.341609,2978.970018,0.000010,16.371736,176.568293,1372.316669,6.167250e-11,5.702615e-12,-3.398719e-11
2019-05-02 16:00:00,208.937062,14568.710514,254.856944,2823.943047,3.635661e-11,10.884275,136.189507,177.538516,1.728596e-11,1.478118e-11,...,2.770935e-11,1036.863843,2180.615366,0.000007,11.984162,129.248542,1004.540092,4.693486e-11,5.702615e-12,-1.508843e-11
2019-05-17 21:00:00,249.465069,17252.842154,301.811655,4047.270119,3.404530e-11,10.303363,128.920840,168.062981,1.607583e-11,1.278584e-11,...,2.301984e-11,1265.537676,2454.545895,0.000008,13.489621,145.484841,1130.731168,5.393226e-11,5.702615e-12,-1.720694e-11
2019-06-02 02:00:00,212.667592,14731.132569,257.698266,4466.080368,2.011214e-11,10.828483,135.491397,176.628450,1.039742e-11,8.687314e-12,...,1.077120e-11,1279.000000,3331.284098,0.000011,18.307973,197.450509,1534.616552,7.332789e-11,5.702615e-12,-4.855889e-11
2019-06-17 07:00:00,210.562194,14554.690065,254.611678,4006.745682,4.035294e-11,13.675370,171.113077,223.065362,1.825237e-11,1.526843e-11,...,1.341367e-11,1279.000000,3350.421457,0.000011,18.413148,198.584811,1543.432524,7.617371e-11,5.702615e-12,-4.256666e-11
2019-07-02 12:00:00,157.953530,10996.887598,192.373455,2417.711057,3.771361e-11,11.238959,140.627487,183.323928,1.798591e-11,1.486712e-11,...,1.519611e-11,1178.886152,3056.134381,0.000010,16.795814,181.141948,1407.863835,7.179404e-11,5.702615e-12,-1.860099e-11
2019-07-17 17:00:00,127.700978,8924.562274,156.121344,1781.322444,3.424912e-11,10.284258,128.681788,167.751349,1.625185e-11,1.304788e-11,...,1.620543e-11,939.530274,3048.519024,0.000010,16.753961,180.690573,1404.355682,7.158754e-11,5.702615e-12,-2.037598e-11
2019-08-01 22:00:00,172.117671,11934.669143,208.778485,1984.902394,3.137993e-11,9.498642,118.851766,154.936797,1.481532e-11,1.217059e-11,...,1.738124e-11,731.456349,3002.200962,0.000010,16.499408,177.945228,1383.018425,6.912608e-11,5.702615e-12,-1.888325e-11
2019-08-17 03:00:00,196.184477,13690.762770,239.498613,1741.594052,2.996301e-11,9.299492,116.359908,151.688378,1.394944e-11,1.124879e-11,...,6.963794e-12,660.730902,2926.842417,0.000010,16.085255,173.478607,1348.303142,6.492043e-11,5.702615e-12,-2.078496e-11
2019-09-01 08:00:00,347.692819,23689.531884,414.411537,2095.872108,1.449843e-11,7.818555,97.829683,127.532121,7.500851e-12,5.953227e-12,...,1.277493e-11,623.908851,2662.674348,0.000009,14.633448,157.820945,1226.609321,5.555599e-11,5.702615e-12,-2.246005e-11
2019-09-16 13:00:00,215.181018,15039.495162,263.092590,1341.920692,1.440727e-11,7.153739,89.511167,116.687989,7.165126e-12,5.451444e-12,...,1.143571e-11,594.724789,2454.796014,0.000008,13.490996,145.499666,1130.846390,4.992261e-11,5.702615e-12,-1.695147e-11
2019-10-01 18:00:00,202.826024,14105.793334,246.758928,2008.988383,9.809367e-12,4.738240,59.287237,77.287658,4.817309e-12,3.539363e-12,...,1.560849e-11,603.403162,2161.015526,0.000007,11.876446,128.086829,995.511069,4.193985e-11,5.702615e-12,-1.415862e-11
2019-10-16 23:00:00,230.253013,15951.272369,279.042715,1476.929806,9.259760e-12,3.310038,41.416851,53.991577,4.172114e-12,2.650353e-12,...,4.562243e-12,610.060098,2126.853984,0.000007,11.688702,126.062020,979.773934,4.013128e-11,5.702615e-12,-1.324439e-11
2019-11-01 04:00:00,221.949841,15416.200784,269.682469,2091.662907,4.165051e-12,1.594040,19.945429,26.001135,1.888450e-12,1.200088e-12,...,4.619702e-11,609.436417,1179.263993,0.000004,6.480964,69.896853,543.249387,2.038840e-11,5.702615e-12,-3.949918e-12
2019-11-16 09:00:00,229.271243,16073.547707,281.181732,2412.145260,2.075859e-12,0.891178,11.150866,14.536422,9.709823e-13,5.486312e-13,...,3.582521e-11,609.827384,1237.205851,0.000004,6.799400,73.331159,569.941356,1.998685e-11,5.702615e-12,-1.253858e-11
2019-12-01 14:00:00,408.630802,27623.082755,483.222895,1539.563504,2.144894e-12,0.958164,11.989023,15.629055,9.602588e-13,5.501924e-13,...,3.048811e-11,631.484024,1196.015707,0.000004,6.573028,70.889754,550.966368,1.882560e-11,5.702615e-12,-1.254131e-11
2019-12-16 19:00:00,251.086418,17116.856533,299.432798,1753.258131,1.835069e-12,0.803613,10.055210,13.108111,8.645561e-13,0.000000e+00,...,5.810934e-11,635.294687,1224.767416,0.000004,6.731041,72.593914,564.211365,1.909111e-11,5.702615e-12,-4.630940e-12

In [25]:
a / b

121.66666666666669

In [26]:
365/3

121.66666666666667